### ISSUE TITLE
openmediavault-cups 3.1.2 bug

### ISSUE THREAD

**Issue by thk70** [OpenMediaVault-Plugin-Developers/openmediavault-cups#16]
Virtual omv 4.1.12 on ESXi vSphere 6 Hypervisor
Trying to enable the plugin "printing" but it errors when click "Save":

Error #0: OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; omv-cups 'enableSharing' 2>&1' with exit code '1': Traceback (most recent call last): File "/usr/sbin/omv-cups", line 305, in <module> apg = OMVCups() File "/usr/sbin/omv-cups", line 73, in __init__ self.conn = cups.Connection() RuntimeError: failed to connect to server in /usr/share/php/openmediavault/system/process.inc:182 Stack trace: #0 /usr/share/openmediavault/engined/rpc/cups.inc(428): OMV\System\Process->execute(Array) #1 /usr/share/openmediavault/engined/rpc/cups.inc(135): OMV\Engined\Rpc\Cups->runCupsCommand('enableSharing') #2 [internal function]: OMV\Engined\Rpc\Cups->setSettings(Array, Array) #3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array) #4 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('setSettings', Array, Array) #5 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('Cups', 'setSettings', Array, Array, 1) #6 [{main}[]

**Comment by dawansch** [comment]
OMV 4.1.17-1 4.9 Linux no Hypervisor

Same issue for me

**Comment by ryecoaaron** [comment]
I looked at this but since I don't use it, I really don't know what is wrong.  This plugin is going away in favor of docker.  I think you would be better trying docker now.

**Comment by dougcooper** [comment]
Im curious what the preferred docker image is for replacing this feature.

**Comment by ryecoaaron** [comment]
I don't use cups but there are some images on docker hub that have 50K+ downloads - https://hub.docker.com/search?q=cups&type=image

**Comment by dougcooper** [comment]
@ryecoaaron thanks for the reply. I messed around with a few, but they either weren't compatible with ARM or they just didnt seem to work. I was able to get the desired AirPrint functionality using this [tutorial](http://linuxwin.com/cups-airprint-on-raspberry-pi/). If I find some time I'll make a docker container and post it here. Suggest this issue is closed.

**Comment by vpistis** [comment]
I have **openmediavault-cups-3.1.2**, for me the error was into the file `/usr/sbin/omv-cups-avahi` at lines 119 and 12:
```
    if not port_no:
        port_no = self.port
```
after comment these lines, cups start correctly.

I hope this helping someone.

**Comment by mattcasey** [comment]
This error seems to imply that the CUPS server is just not running. It happened to me after upgrading from OMV 3.x to 4x. I uninstalled the cups plugin first and re-installed, and tried the fix from @vpistis but it didn't help. I finally just ran `sudo systemctl restart cups.service` and voila! I was able to enable the OMV plugin and it recognized the printer I previously had set up.

**Comment by HAMSoft-Hank** [comment]
Thanks mattcasey. You're systemctl command worked for me. I did not employ vpistis's suggestion, only yours, and I'm up and running now.

**Comment by flytomoon2021** [comment]
Hi,
thanks to vpistis I managed to get my printer with my omv 4.1.35-1 visible in my network. I can print from localhost:631 test pages and via line command (with lp cups.conf for example). 
On my Windows 10 computer and on my Iphone the printer shows up but doesn't print. On the Windows 10 system there is an error message "Document could not be printed" and "An error occurred during printing". 
On the Iphone  I can select the Airprint Printer correctly. When I start printing,  a messege indicates that Iphone tries to connect to the printer, but nothing happens.
On the localhost:631 page for admin  the printer is listed. 
Features are: Idling, ready to take orders, ****no network release**** standard printer, colour management. I have tried several times as an admin to change to "network release active" but I failed. It simply doesn't change.
Can anybody give me an advice where I can change this ???

**Comment by lrxianed** [comment]
thx @vpistis @mattcasey ,it work.
